=== jgilabert147/tema03/Ejercicio_boletin2/Ejercicio2/Ejercicio_Minecraft_2.dtd
<!ELEMENT minecraftItems (item+)>
    <!ELEMENT item (name, type, damage?, description, materials, enchantments)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT damage (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT materials (material+)?>
            <!ELEMENT material (#PCDATA)>
        <!ELEMENT enchantments (enchantment+)?>
            <!ELEMENT enchantment (#PCDATA)>

<!ATTLIST minecraftItems lang CDATA #REQUIRED>
<!ATTLIST item id ID #REQUIRED
               rarity (comun|raro|epico) #REQUIRED
               crafteable (true|false) #REQUIRED
               enchantable (true|false) #REQUIRED
               N.usos CDATA #REQUIRED>

=== jgilabert147/tema03/Ejercicio_boletin2/Ejercicio2/Ejercicio_Minecraft_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minecraftItems SYSTEM "Ejercicio_Minecraft_2.dtd">

<minecraftItems lang="es">

    <item id="_01" rarity="comun" crafteable="true" enchantable="true" N.usos="2100">
        <name>Espada de Netherite</name>
        <type>Arma</type>
        <damage>8 corazones</damage>
        <description>Arma cuerpo a cuerpo, utilizadas principalmente para atacar a criaturas o jugadores.</description>
        <materials>
            <material>1 Palo</material>
            <material>2 Lingotes de Netherite</material>
        </materials>
        <enchantments>
            <enchantment>Aspecto Igneo</enchantment>
            <enchantment>Afilado</enchantment>
        </enchantments>
    </item>

    <item id="_02" rarity="comun" crafteable="true" enchantable="true" N.usos="1524">
        <name>Pala de diamane</name>
        <type>Herramienta</type>
        <damage>4 Corazones</damage>
        <description>Herramienta que ayuda en el proceso de excavacion y recoleccion de tierr, arena, grava, arcilla y nieve.</description>
        <materials>
            <material>1 Palo</material>
            <material>2 Diamantes</material>
        </materials>
            <enchantments>
                <enchantment>Eficiencia</enchantment>
                <enchantment>Irompible</enchantment>
            </enchantments>
    </item>

    <item id="_03" rarity="comun" crafteable="true" enchantable="true" N.usos="500">
        <name>Arco</name>
        <type>Arma</type>
        <damage>9 Corazones si esta tensado al maximo</damage>
        <description>Arma que permite disparar flechas</description>
        <materials>
            <material>3 palos</material>
            <material>3 hilos</material>
        </materials>
        <enchantments>
            <enchantment>Infinidad</enchantment>
            <enchantment>Reparacion</enchantment>
        </enchantments>
    </item>
    
</minecraftItems>
