=== jgilabert147/tema03/Ejercicio_boletin2/Ejercicio5/Ejercicio_CV.dtd
<!ELEMENT CV (info-personal, acerca, idiomas, contacto, educacion, experiencias, habilidades)>
    
    <!ELEMENT info-personal (nombre, apellidos, licenciatura, fecha-nacimiento)>
        <!ATTLIST info-personal 
            genero CDATA #REQUIRED
            nacionalidad CDATA #REQUIRED>

        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT licenciatura (#PCDATA)>
        <!ELEMENT fecha-nacimiento (#PCDATA)>

    <!ELEMENT acerca (#PCDATA)>

    <!ELEMENT idiomas (idioma+)>
        <!ELEMENT idioma (#PCDATA)>
        <!ATTLIST idioma 
            nombre CDATA #REQUIRED
            nivel (Nativo | A2 | B1 | B2 | C1 | C2) #REQUIRED>

    <!ELEMENT contacto (tel, direccion, email)>
        <!ELEMENT tel (#PCDATA)>
            <!ATTLIST tel tipo (Movil | Fijo) #IMPLIED>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT email (#PCDATA)>

    <!ELEMENT educacion (titulacion+)>
        <!ELEMENT titulacion (nombre, lugar, tiempo)>
        <!ATTLIST titulacion nivel (Secundaria | Grado-Basico | Grado-Medio | Grado-Superior | Especializacion | Batchillerato | Grado-Universitario | Master) #REQUIRED>
            <!ELEMENT lugar (#PCDATA)>
            <!ELEMENT tiempo (#PCDATA)>

    <!ELEMENT experiencias (experiencia+)>
        <!ELEMENT experiencia (nombre, lugar, desde, hasta, descripcion)>
            <!ELEMENT desde (#PCDATA)>
            <!ELEMENT hasta (#PCDATA)>
            <!ELEMENT descripcion (#PCDATA)>

    <!ELEMENT habilidades (habilidad+)>
        <!ELEMENT habilidad (#PCDATA)>

=== jgilabert147/tema03/Ejercicio_boletin2/Ejercicio5/Ejercicio_CV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CV SYSTEM "Ejercicio_CV.dtd">

<CV>

    <info-personal genero="Masculino" nacionalidad="Española">
        <nombre>Jacob</nombre>
        <apellidos>Gilabert Lucas</apellidos>
        <licenciatura>Técnico en Sistemas Microinformaticos y Redes</licenciatura>
        <fecha-nacimiento>26/11/2006</fecha-nacimiento>
    </info-personal>

    <acerca>
        Lorem ipsum dolor sit amet. Est Quis consequatur in dolorum enim ut suscipit 
        omnis qui enim dicta et Quis natus et accusamus quibusdam quo nostrum iure. 
        Ex consequatur dolores est voluptatum iusto est asperiores nihil. 
    </acerca>

    <idiomas>
        <idioma nombre="Castellano" nivel="Nativo"/>
        <idioma nombre="Valenciano" nivel="Nativo"/>
        <idioma nombre="Ingles" nivel="B1"/>
    </idiomas>

    <contacto>
        <tel tipo="Movil">+34 6XX XX XX XX</tel>
        <direccion>Av. xxxxxxx xxxxxxx XX</direccion>
        <email>jacobgilabert@gmail.com</email>
    </contacto>

    <educacion>

        <titulacion nivel="Secundaria">
            <nombre>ESO</nombre>
            <lugar>IES Pedreguer</lugar>
            <tiempo>2018-2022</tiempo>
        </titulacion>

        <titulacion nivel="Grado-Medio">
            <nombre>SMR</nombre>
            <lugar>IES La Mar</lugar>
            <tiempo>2022-2024</tiempo>
        </titulacion>

        <titulacion nivel="Grado-Superior">
            <nombre>ASIR</nombre>
            <lugar>IES La Mar</lugar>
            <tiempo>2024-202X</tiempo>
        </titulacion>

    </educacion>

    <experiencias>

        <experiencia>
            <nombre>Tecnico Informatico en redes</nombre>
            <lugar>UPI Ondara</lugar>
            <desde>20-03-2024</desde>
            <hasta>13-06-2024</hasta>
            <descripcion>Lorem ipsum dolor sit amet.</descripcion>
        </experiencia>

    </experiencias>

    <habilidades>
        <habilidad>Comunicacion</habilidad>
        <habilidad>Resolucion de problemas</habilidad>
        <habilidad>Comunicacion</habilidad>
        <habilidad>Creatividad</habilidad>
        <habilidad>Pensamiento estrategico</habilidad>
    </habilidades>

</CV>
