=== jgilabert147/tema03/Ejercicio_boletin2/Ejercicio6/Ejercicio_Listado_Tickets.dtd
<!ELEMENT tickets (membrete, ticket+)>
    <!ELEMENT membrete (razon_social, cif, paginaWeb, sucursal)>
        <!ELEMENT razon_social (#PCDATA)>
        <!ELEMENT cif (#PCDATA)>
        <!ELEMENT paginaWeb (#PCDATA)>
        <!ELEMENT sucursal (codigoSucursal, nombreSucursal, direccion, codigoPostal, poblacion, telefonos)>
            <!ELEMENT codigoSucursal (#PCDATA)>
            <!ELEMENT nombreSucursal (#PCDATA)>
            <!ELEMENT direccion (#PCDATA)>
            <!ELEMENT codigoPostal (#PCDATA)>
            <!ELEMENT poblacion (#PCDATA)>    
            <!ELEMENT telefonos (telefono+)>
                <!ELEMENT telefono (#PCDATA)>
                
    <!ELEMENT ticket (cabecera, lineas, resumen)>
        <!ELEMENT cabecera (fecha, hora, empleado)>
            <!ELEMENT fecha (#PCDATA)>
            <!ELEMENT hora (#PCDATA)>
            <!ELEMENT empleado (#PCDATA)>
        <!ELEMENT lineas (linea+)>
            <!ELEMENT linea (cantidad, descripcion, precio-unitario, importe)>
                <!ELEMENT cantidad (#PCDATA)>
                <!ELEMENT descripcion (#PCDATA)>
                <!ELEMENT precio-unitario (#PCDATA)>
                <!ELEMENT importe (#PCDATA)>
        <!ELEMENT resumen (forma_pago, total)>
            <!ELEMENT forma_pago (#PCDATA)>
            <!ELEMENT total (#PCDATA)>

<!ATTLIST telefono tipo (fijo | movil) #REQUIRED>
<!ATTLIST cabecera id ID #REQUIRED>
<!ATTLIST linea codigo ID #REQUIRED>

=== jgilabert147/tema03/Ejercicio_boletin2/Ejercicio6/Ejercicio_Listado_Tickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tickets SYSTEM "Ejercicio_Listado_Tickets.dtd">

<tickets>

    <membrete>
        <razon_social>Materiales Oficina X  </razon_social>
        <cif>A12345678</cif>
        <paginaWeb>www.materialx.com</paginaWeb>
        <sucursal>
            <codigoSucursal>001</codigoSucursal>
            <nombreSucursal>Sucursal Centro</nombreSucursal>
            <direccion>Calle Mayor 10</direccion>
            <codigoPostal>28001</codigoPostal>
            <poblacion>Madrid</poblacion>
            <telefonos>
                <telefono tipo="fijo">912345678</telefono>
                <telefono tipo="movil">622334455</telefono>
            </telefonos>
        </sucursal>
    </membrete>

    <ticket>

        <cabecera id="_01">
            <fecha>22-06-2024</fecha>
            <hora>11:30</hora>
            <empleado>Juan Perez</empleado>
        </cabecera>

        <lineas>
            <linea codigo="_0A">
                <cantidad>3</cantidad>
                <descripcion>paquete de folios</descripcion>
                <precio-unitario>4,50</precio-unitario>
                <importe>13,50</importe>
            </linea>
        </lineas>

        <resumen>
            <forma_pago>tarjeta</forma_pago>
            <total>13,50</total>
        </resumen>

    </ticket>

</tickets>
